name: Metrics

on:
  schedule: [{ cron: "0 * * * *" }] # every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_stargazers: yes
          plugin_followup: yes
