name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]  # Update every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🧮 Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo

      - name: 🚀 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: metrics.svg
